# Generated by Django 3.2.8 on 2021-10-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userdev_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdev',
            name='technology',
            field=models.ManyToManyField(blank=True, related_name='users', to='profiles.Technology', verbose_name='Технологии'),
        ),
    ]
